- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: adding nodejs from node source
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: installing nodejs 13
  apt:
    name: 
      - nodejs
    state: latest
    update_cache: true


- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: pm2 installation
  npm:
    name: pm2
    state: present
    global: yes
    production: yes
